# Generated by Django 3.0.6 on 2020-05-06 08:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20200506_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI', 'Artificial Intelligence / Machine Learning'), ('IO', 'Internet of Things'), ('CE', 'Cloud enablement'), ('BC', 'Blockchain'), ('DV', 'Application Development'), ('DP', 'Application Deployment'), ('MN', 'Application Maintenance'), ('DS', 'Data Scientists'), ('CN', 'IT Consulting'), ('SM', 'IT Services Management'), ('SS', 'IT Support Services / Help Desk'), ('MS', 'Infrastructure Management Services'), ('IS', 'Information Security'), ('BM', 'Business Process Management'), ('PM', 'Project Management'), ('SL', 'Sales and Pre Sales'), ('SA', 'Solutions Architecting'), ('TS', 'Testing and Quality Assurance'), ('OT', 'Other')], max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SD', 'Software Developer'), ('UI', 'UI Developer'), ('WD', 'Web Developer'), ('MD', 'Media Developer'), ('TW', 'Technical Writer'), ('DE', 'Deployment Engineer'), ('MN', 'Application Maintenance Engineer'), ('DA', 'Data Associate'), ('ML', 'Machine Learning Expert'), ('BA', 'Business Analyst'), ('TS', 'Engineer Technical Support - Level 1 & 2'), ('IE', 'Infrastructure Engineer'), ('SC', 'Security Analyst'), ('SA', 'Sales and Pre Sales Analyst'), ('TE', 'Test Engineer'), ('QA', 'QA Engineer'), ('BO', 'Back office Associates'), ('CS', 'Customer Service Associates'), ('OT', 'Other')], max_length=500),
        ),
    ]
